<h1><center>Survey Data Wrangler</center></h1>
<center>Rock n Ribs</center>

On this notebook I analyze the customer satisfaction surveys from Rock n Ribs restaurant since October 2019 until May 2020 looking up trends or variations from the 1st semester operation of the year. The dataset is given by Survey Monkey platform and the aim of this analysis is cross this data with Facebook campaigns dataset to find hidden patterns.

In [1]:
import pandas as pd
import numpy as np

<b>Note: </b>From data privacy issues, I only show the firstly three rows of my dataset anytime. But you can look that this dataset has 4845 useful rows.

In [2]:
df_survey = pd.read_csv('./survey_05_05_2020.csv')
df_survey[0:4]

,respondent_id,collector_id,date_created,date_modified,ip_address,email_address,first_name,last_name,custom_1,¿En qué Franquicia ROCK n RIBS te encuentras?,...,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,¿TE INTERESA UNA FRANQUICIA ROCK n RIBS?,Unnamed: 37,Unnamed: 38
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Response,...,Cumpleaños,Ciudad/Localidad donde radica,Ciudad donde le interesa poner una Franquicia ...,Código postal,País,E-mail,Celular a 10 dígitos,SÍ,NO,Ciudad donde le interesa una Franquicia ROCK n...
1,1.145620e+10,249027193.0,03/29/2020 01:13:21 AM,03/29/2020 04:09:53 AM,189.183.129.231,NaN,NaN,NaN,NaN,"San Luis Potosí, Slp.",...,06/07/98,NaN,NaN,NaN,NaN,nigoarmando@gmail.com,4441468605,SÍ,NaN,NaN
2,1.145600e+10,249027193.0,03/29/2020 12:37:27 AM,03/29/2020 01:12:43 AM,189.183.129.231,NaN,NaN,NaN,NaN,"San Luis Potosí, Slp.",...,17 julio 99,NaN,NaN,NaN,NaN,liza.diazdeleon@hotmail.com,NaN,NaN,NO,NaN
3,1.145595e+10,249027193.0,03/29/2020 12:20:21 AM,03/29/2020 12:33:51 AM,189.183.129.231,NaN,NaN,NaN,NaN,"San Luis Potosí, Slp.",...,02 de septiembre,NaN,NaN,NaN,NaN,beatrizmh.bh@gmail..com,4444894280,NaN,NO,NaN

In [3]:
df_survey.columns

Index(['respondent_id', 'collector_id', 'date_created', 'date_modified',
       'ip_address', 'email_address', 'first_name', 'last_name', 'custom_1',
       '¿En qué Franquicia ROCK n RIBS te encuentras?',
       ' ¿Qué tan probable es que recomiendes ROCK n RIBS a tus amigos o colegas?',
       '¿Qué te pareció la comida en general? Seleccione 1 respuesta.',
       '¿Qué te parecieron las bebidas en general? Seleccione 1 respuesta',
       '¿Cómo calificaría la relación calidad precio de nuestros alimentos y bebidas.?',
       '¿Qué tan atento ha sido su mesero ante sus necesidades durante su visita en ROCK n RIBS?',
       'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18',
       '¿Cúal es el nombre de su mesero?',
       '¿El (La) Gerente se acercó en algún momento a su mesa y estuvo atento(a) a sus necesidades?',
       '¿Cuál el nombre de su Gerente?',
       '¿Cuánto tiempo ha sido cliente de ROCK n RIBS?',
       '¿Cómo te enteraste de nosotros?', 'Unnamed: 24',
       '¿Tienes algún otro comentario, pregunta, queja, sugerencia o inquietud?',
       'Información de contacto', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35',
       '¿TE INTERESA UNA FRANQUICIA ROCK n RIBS?', 'Unnamed: 37',
       'Unnamed: 38'],
      dtype='object')

In [4]:
# Cleaning column's names
df_survey.rename(columns={'¿En qué Franquicia ROCK n RIBS te encuentras?':'Franquicia',
        ' ¿Qué tan probable es que recomiendes ROCK n RIBS a tus amigos o colegas?':'Recomendacion',
        '¿Qué te pareció la comida en general? Seleccione 1 respuesta.': 'Comida',
        '¿Qué te parecieron las bebidas en general? Seleccione 1 respuesta': 'Bebida',
        '¿Cómo calificaría la relación calidad precio de nuestros alimentos y bebidas.?':'CalidadPrecio',
        '¿Qué tan atento ha sido su mesero ante sus necesidades durante su visita en ROCK n RIBS?':'AtencionMesero(E)',
        'Unnamed: 15':'AtencionMesero(B)',
        'Unnamed: 16':'AtencionMesero(R)',
        'Unnamed: 17':'AtencionMesero(M)',
        'Unnamed: 18':'NombreMeseroVacio',
        '¿Cúal es el nombre de su mesero?':'NombreMesero', 
        '¿El (La) Gerente se acercó en algún momento a su mesa y estuvo atento(a) a sus necesidades?':'AtencionGerente',
        '¿Cuál el nombre de su Gerente?':'NombreGerente',
        '¿Cuánto tiempo ha sido cliente de ROCK n RIBS?':'TiempoSerCliente',
        '¿Cómo te enteraste de nosotros?':'MedCon',
        'Unnamed: 24':'OtroMedCon',
        '¿Tienes algún otro comentario, pregunta, queja, sugerencia o inquietud?':'Comentarios',
        'Información de contacto':'NombreCliente',
        'Unnamed: 27':'OcupacionVacio',
        'Unnamed: 28':'EmailVacio',        
        'Unnamed: 29':'Cumpleanos',                          
        'Unnamed: 30':'CiudadCliente',
        'Unnamed: 31':'CiudadDeseoFranqVacio',                          
        'Unnamed: 32':'CP',  
        'Unnamed: 33':'Pais',                            
        'Unnamed: 34':'Email',                         
        'Unnamed: 35':'Celular',
        '¿TE INTERESA UNA FRANQUICIA ROCK n RIBS?':'DeseoFranq(SI)',
        'Unnamed: 37':'DeseoFranq(NO)',
        'Unnamed: 38':'CiudadDeseoFranq'}, inplace = True)
df_survey.head()

,respondent_id,collector_id,date_created,date_modified,ip_address,email_address,first_name,last_name,custom_1,Franquicia,...,Cumpleanos,CiudadCliente,CiudadDeseoFranqVacio,CP,Pais,Email,Celular,DeseoFranq(SI),DeseoFranq(NO),CiudadDeseoFranq
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Response,...,Cumpleaños,Ciudad/Localidad donde radica,Ciudad donde le interesa poner una Franquicia ...,Código postal,País,E-mail,Celular a 10 dígitos,SÍ,NO,Ciudad donde le interesa una Franquicia ROCK n...
1,1.145620e+10,249027193.0,03/29/2020 01:13:21 AM,03/29/2020 04:09:53 AM,189.183.129.231,NaN,NaN,NaN,NaN,"San Luis Potosí, Slp.",...,06/07/98,NaN,NaN,NaN,NaN,nigoarmando@gmail.com,4441468605,SÍ,NaN,NaN
2,1.145600e+10,249027193.0,03/29/2020 12:37:27 AM,03/29/2020 01:12:43 AM,189.183.129.231,NaN,NaN,NaN,NaN,"San Luis Potosí, Slp.",...,17 julio 99,NaN,NaN,NaN,NaN,liza.diazdeleon@hotmail.com,NaN,NaN,NO,NaN
3,1.145595e+10,249027193.0,03/29/2020 12:20:21 AM,03/29/2020 12:33:51 AM,189.183.129.231,NaN,NaN,NaN,NaN,"San Luis Potosí, Slp.",...,02 de septiembre,NaN,NaN,NaN,NaN,beatrizmh.bh@gmail..com,4444894280,NaN,NO,NaN
4,1.145594e+10,249027193.0,03/28/2020 11:49:31 PM,03/29/2020 12:20:16 AM,189.183.129.231,NaN,NaN,NaN,NaN,"San Luis Potosí, Slp.",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NO,NaN

In [5]:
df_survey.drop([0],axis=0, inplace=True)
df_survey[0:3]

,respondent_id,collector_id,date_created,date_modified,ip_address,email_address,first_name,last_name,custom_1,Franquicia,...,Cumpleanos,CiudadCliente,CiudadDeseoFranqVacio,CP,Pais,Email,Celular,DeseoFranq(SI),DeseoFranq(NO),CiudadDeseoFranq
1,1.145620e+10,249027193.0,03/29/2020 01:13:21 AM,03/29/2020 04:09:53 AM,189.183.129.231,NaN,NaN,NaN,NaN,"San Luis Potosí, Slp.",...,06/07/98,NaN,NaN,NaN,NaN,nigoarmando@gmail.com,4441468605,SÍ,NaN,NaN
2,1.145600e+10,249027193.0,03/29/2020 12:37:27 AM,03/29/2020 01:12:43 AM,189.183.129.231,NaN,NaN,NaN,NaN,"San Luis Potosí, Slp.",...,17 julio 99,NaN,NaN,NaN,NaN,liza.diazdeleon@hotmail.com,NaN,NaN,NO,NaN
3,1.145595e+10,249027193.0,03/29/2020 12:20:21 AM,03/29/2020 12:33:51 AM,189.183.129.231,NaN,NaN,NaN,NaN,"San Luis Potosí, Slp.",...,02 de septiembre,NaN,NaN,NaN,NaN,beatrizmh.bh@gmail..com,4444894280,NaN,NO,NaN

In [6]:
df_survey.shape

(4845, 39)

In [7]:
# Verifying null values
df_survey.isna().sum()

respondent_id               0
collector_id                0
date_created                0
date_modified               0
ip_address                  0
email_address            4845
first_name               4845
last_name                4845
custom_1                 4845
Franquicia                 43
Recomendacion               0
Comida                     21
Bebida                     26
CalidadPrecio              33
AtencionMesero(E)        1559
AtencionMesero(B)        3504
AtencionMesero(R)        4626
AtencionMesero(M)        4820
NombreMeseroVacio        3233
NombreMesero             3157
AtencionGerente          2266
NombreGerente            3867
TiempoSerCliente          230
MedCon                     98
OtroMedCon               4703
Comentarios              2140
NombreCliente            1745
OcupacionVacio           4845
EmailVacio               4845
Cumpleanos               2377
CiudadCliente            4845
CiudadDeseoFranqVacio    4845
CP                       4845
Pais                     4845
Email                    2536
Celular                  2669
DeseoFranq(SI)           3950
DeseoFranq(NO)            912
CiudadDeseoFranq         4487
dtype: int64

In [8]:
# Cleaning our dataset of null mayority columns
df_survey.drop(['email_address', 
                'first_name', 
                'last_name', 
                'custom_1', 
                'OcupacionVacio', 
                'EmailVacio', 
                'CiudadCliente',
                'CiudadDeseoFranqVacio',
                'CP',
                'Pais'], axis=1, inplace=True)
df_survey.isna().sum()

respondent_id           0
collector_id            0
date_created            0
date_modified           0
ip_address              0
Franquicia             43
Recomendacion           0
Comida                 21
Bebida                 26
CalidadPrecio          33
AtencionMesero(E)    1559
AtencionMesero(B)    3504
AtencionMesero(R)    4626
AtencionMesero(M)    4820
NombreMeseroVacio    3233
NombreMesero         3157
AtencionGerente      2266
NombreGerente        3867
TiempoSerCliente      230
MedCon                 98
OtroMedCon           4703
Comentarios          2140
NombreCliente        1745
Cumpleanos           2377
Email                2536
Celular              2669
DeseoFranq(SI)       3950
DeseoFranq(NO)        912
CiudadDeseoFranq     4487
dtype: int64

In [9]:
# Unifying AtencionMesero divided columns
am_e = np.array(df_survey['AtencionMesero(E)'])
am_b = np.array(df_survey['AtencionMesero(B)'])
am_r = np.array(df_survey['AtencionMesero(R)'])
am_m = np.array(df_survey['AtencionMesero(M)'])

am_list = []
for i in range(0, (df_survey.shape[0])):
    if am_e[i] == 'Excelente':
        am_list.append('Excelente')
    else:
        if am_b[i] == 'Bueno':
            am_list.append('Bueno')
        else:
            if am_r[i] == 'Regular':
                am_list.append('Regular')
            else:
                if am_r[i] == 'Malo':
                    am_list.append('Malo')
                else:
                    am_list.append(None)
len(am_list)

4845

In [10]:
df_survey['AtencionMesero'] = am_list

In [11]:
df_survey.drop(['AtencionMesero(E)', 'AtencionMesero(B)', 'AtencionMesero(R)', 'AtencionMesero(M)'],axis=1, inplace=True)

In [12]:
df_survey.columns

Index(['respondent_id', 'collector_id', 'date_created', 'date_modified',
       'ip_address', 'Franquicia', 'Recomendacion', 'Comida', 'Bebida',
       'CalidadPrecio', 'NombreMeseroVacio', 'NombreMesero', 'AtencionGerente',
       'NombreGerente', 'TiempoSerCliente', 'MedCon', 'OtroMedCon',
       'Comentarios', 'NombreCliente', 'Cumpleanos', 'Email', 'Celular',
       'DeseoFranq(SI)', 'DeseoFranq(NO)', 'CiudadDeseoFranq',
       'AtencionMesero'],
      dtype='object')

In [13]:
df_survey.count()

respondent_id        4845
collector_id         4845
date_created         4845
date_modified        4845
ip_address           4845
Franquicia           4802
Recomendacion        4845
Comida               4824
Bebida               4819
CalidadPrecio        4812
NombreMeseroVacio    1612
NombreMesero         1688
AtencionGerente      2579
NombreGerente         978
TiempoSerCliente     4615
MedCon               4747
OtroMedCon            142
Comentarios          2705
NombreCliente        3100
Cumpleanos           2468
Email                2309
Celular              2176
DeseoFranq(SI)        895
DeseoFranq(NO)       3933
CiudadDeseoFranq      358
AtencionMesero       4797
dtype: int64

In [14]:
# Unifying DeseoFranq divided columns
df_s = np.array(df_survey['DeseoFranq(SI)'])
df_n = np.array(df_survey['DeseoFranq(NO)'])

In [15]:
df_list = []
for i in range(0, (df_survey.shape[0])):
    if df_s[i] == 'SÍ':
        df_list.append('SI')
    else:
        df_list.append('NO')

len(df_list)

4845

In [16]:
df_survey['DeseoFranq'] = df_list
df_survey.drop(['DeseoFranq(SI)', 'DeseoFranq(NO)'],axis=1, inplace=True)

In [17]:
df_survey.columns

Index(['respondent_id', 'collector_id', 'date_created', 'date_modified',
       'ip_address', 'Franquicia', 'Recomendacion', 'Comida', 'Bebida',
       'CalidadPrecio', 'NombreMeseroVacio', 'NombreMesero', 'AtencionGerente',
       'NombreGerente', 'TiempoSerCliente', 'MedCon', 'OtroMedCon',
       'Comentarios', 'NombreCliente', 'Cumpleanos', 'Email', 'Celular',
       'CiudadDeseoFranq', 'AtencionMesero', 'DeseoFranq'],
      dtype='object')

In [18]:
df_survey.count()

respondent_id        4845
collector_id         4845
date_created         4845
date_modified        4845
ip_address           4845
Franquicia           4802
Recomendacion        4845
Comida               4824
Bebida               4819
CalidadPrecio        4812
NombreMeseroVacio    1612
NombreMesero         1688
AtencionGerente      2579
NombreGerente         978
TiempoSerCliente     4615
MedCon               4747
OtroMedCon            142
Comentarios          2705
NombreCliente        3100
Cumpleanos           2468
Email                2309
Celular              2176
CiudadDeseoFranq      358
AtencionMesero       4797
DeseoFranq           4845
dtype: int64

In [19]:
# Unifying DeseoFranq divided columns
nm_c = np.array(df_survey['NombreMesero'])
nm_v = np.array(df_survey['NombreMeseroVacio'])

nm_list = []
for i in range(0, (df_survey.shape[0])):
    if type(nm_c[i])==str:
        nm_list.append(nm_c[i])
    else:
        if type(nm_v[i]==str):
            nm_list.append(nm_v[i])
        else:
            nm_list.append(None)

len(nm_list)

4845

In [20]:
df_survey['NomMesero'] = nm_list
df_survey.drop(['NombreMesero', 'NombreMeseroVacio'],axis=1, inplace=True)

In [21]:
df_survey[0:3]

,respondent_id,collector_id,date_created,date_modified,ip_address,Franquicia,Recomendacion,Comida,Bebida,CalidadPrecio,...,OtroMedCon,Comentarios,NombreCliente,Cumpleanos,Email,Celular,CiudadDeseoFranq,AtencionMesero,DeseoFranq,NomMesero
1,1.145620e+10,249027193.0,03/29/2020 01:13:21 AM,03/29/2020 04:09:53 AM,189.183.129.231,"San Luis Potosí, Slp.",10,Excelente,Excelente,Excelente,...,NaN,No,Armando Nigo,06/07/98,nigoarmando@gmail.com,4441468605,NaN,Bueno,SI,Gerardo
2,1.145600e+10,249027193.0,03/29/2020 12:37:27 AM,03/29/2020 01:12:43 AM,189.183.129.231,"San Luis Potosí, Slp.",9,Excelente,Excelente,Promedio,...,NaN,No,Liza,17 julio 99,liza.diazdeleon@hotmail.com,NaN,NaN,Bueno,NO,Alejandro
3,1.145595e+10,249027193.0,03/29/2020 12:20:21 AM,03/29/2020 12:33:51 AM,189.183.129.231,"San Luis Potosí, Slp.",10,Excelente,Excelente,Excelente,...,NaN,Deberían de poner un escenario y un día a la s...,Beatriz Martínez,02 de septiembre,beatrizmh.bh@gmail..com,4444894280,NaN,Excelente,NO,No recuerdo

In [22]:
# Organize the columns
df_survey = df_survey[['respondent_id', 
                       'collector_id',
                       'date_created',
                       'date_modified',
                       'ip_address',
                       'NombreCliente',
                       'Email',
                       'Celular',
                       'Franquicia',
                       'Recomendacion',
                       'Comida',
                       'Bebida',
                       'CalidadPrecio',
                       'TiempoSerCliente',
                       'MedCon',
                       'OtroMedCon',
                       'AtencionMesero',
                       'NomMesero',
                       'AtencionGerente',
                       'NombreGerente',
                       'DeseoFranq',
                       'CiudadDeseoFranq',
                       'Comentarios']]
df_survey[0:3]

,respondent_id,collector_id,date_created,date_modified,ip_address,NombreCliente,Email,Celular,Franquicia,Recomendacion,...,TiempoSerCliente,MedCon,OtroMedCon,AtencionMesero,NomMesero,AtencionGerente,NombreGerente,DeseoFranq,CiudadDeseoFranq,Comentarios
1,1.145620e+10,249027193.0,03/29/2020 01:13:21 AM,03/29/2020 04:09:53 AM,189.183.129.231,Armando Nigo,nigoarmando@gmail.com,4441468605,"San Luis Potosí, Slp.",10,...,Seis meses a un año,Publicidad,NaN,Bueno,Gerardo,Sí,José Luis,SI,NaN,No
2,1.145600e+10,249027193.0,03/29/2020 12:37:27 AM,03/29/2020 01:12:43 AM,189.183.129.231,Liza,liza.diazdeleon@hotmail.com,NaN,"San Luis Potosí, Slp.",9,...,Esta es mi primera visita,Lo ví,NaN,Bueno,Alejandro,No,No se,NO,NaN,No
3,1.145595e+10,249027193.0,03/29/2020 12:20:21 AM,03/29/2020 12:33:51 AM,189.183.129.231,Beatriz Martínez,beatrizmh.bh@gmail..com,4444894280,"San Luis Potosí, Slp.",10,...,Esta es mi primera visita,"Redes sociales (facebook, twitter, instagram)",NaN,Excelente,No recuerdo,No,Desconozco,NO,NaN,Deberían de poner un escenario y un día a la s...

In [23]:
# Export like a CSV file
df_survey.to_csv('./rnr_survey_master_table.csv')